version: '3'
# Add your networks/volumes/services for your microservice

services:
    micro-ci-scheduler:
        image: esgimicroci/al2-scheduler
        container_name: al2-scheduler
        restart: always
        networks:
            - goyave-backend
        ports:
            - '80:80'
        depends_on:
            - postgres
        volumes:
            - .:/app
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        networks:
            - goyave-backend
        restart: always
        volumes:
            - databaseVolume:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD", 'pg_isready -U postgres'] 
            interval: 5s
            timeout: 10s
            retries: 20                
volumes:
    databaseVolume: {}
networks:
    goyave-backend:
        driver: bridge
