name: ESGI Micro CI Scheduler deploy

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*.*.*'

jobs:
  deploy:
    name: Build/Publish Docker Images & Deploy to Azure VM
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: micro-ci-al2/micro-ci-scheduler
        tag_with_ref: true
        dockerfile: Dockerfile.prod
        build_args: RABBIT_MQ_HOSTNAME=${{secrets.RABBIT_MQ_HOSTNAME}},RABBIT_MQ_USERNAME=${{secrets.RABBIT_MQ_USERNAME}},RABBIT_MQ_PORT=${{secrets.RABBIT_MQ_PORT}},RABBIT_MQ_PASSWORD=${{secrets.RABBIT_MQ_PASSWORD}},CONSUL_HOSTNAME=${{secrets.CONSUL_HOSTNAME}},DB_HOSTNAME=${{secrets.DB_HOSTNAME}},DB_PORT=${{secrets.DB_PORT}},DB_USERNAME=${{secrets.DB_USERNAME}},DB_NAME=${{secrets.DB_NAME}},DB_PASSWORD=${{secrets.DB_PASSWORD}},CONSUL_TOKEN=${{secrets.CONSUL_TOKEN}},

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm run-command invoke \
          -g ${{ secrets.AZURE_RESOURCE_GRP }} \ 
          -n ${{ secrets.AZURE_VM }} \
          --command-id RunShellScript --scripts \
          "cd ${{ secrets.FOLDER_PATH }} \
          && export RABBIT_MQ_USERNAME=${{secrets.RABBIT_MQ_USERNAME}} \
          && export RABBIT_MQ_HOSTNAME=${{secrets.RABBIT_MQ_HOSTNAME}} \
          && export RABBIT_MQ_PASSWORD=${{secrets.RABBIT_MQ_PASSWORD}} \
          && export RABBIT_MQ_PORT=${{secrets.RABBIT_MQ_PORT}} \
          && export CONSUL_HOSTNAME=${{secrets.CONSUL_HOSTNAME}} \
          && export CONSUL_TOKEN=${{secrets.CONSUL_TOKEN}} \
          && export DB_HOSTNAME=${{secrets.DB_HOSTNAME}} \
          && export DB_PORT=${{secrets.DB_PORT}} \
          && export DB_USERNAME=${{secrets.DB_USERNAME}} \
          && export DB_PASSWORD=${{secrets.DB_PASSWORD}} \
          && export DB_NAME=${{secrets.DB_NAME}} \ 
          && wget -q https://raw.githubusercontent.com/esgi-microservices-al2/micro-ci-scheduler/master/.github/azure/docker-compose.yml -O docker-compose.yml \ 
          && docker-compose stop \
          && docker-compose rm \
          && docker-compose up -d"